version: 2
updates:
  - package-ecosystem: npm
    directory: /
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
      - dependency-name: '@kubernetes/client-node'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    schedule:
      interval: monthly
