version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  nomis-user-roles-api:
    image: quay.io/hmpps/nomis-user-roles-api:latest
    networks:
      - hmpps
    container_name: nomis-user-roles-api
    ports:
      - '8102:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health/ping']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    depends_on: [nomis-user-roles-api]
    ports:
      - '9090:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SPRING_PROFILES_ACTIVE=dev,nomis
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - NOMIS_ENDPOINT_URL=http://nomis-user-roles-api:8080

  minio:
    image: minio/minio
    command: server --console-address :9001 /data
    networks:
      - hmpps
    container_name: minio
    restart: always
    environment:
      - MINIO_REGION_NAME=eu-west-2
      - MINIO_ROOT_USER=TEST_MINIO_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=TEST_MINIO_SECRET_KEY
    ports:
      - '9000:9000'
      - '9001:9001'

  minio-init:
    image: minio/mc
    networks:
      - hmpps
    container_name: minio-init
    depends_on:
      - minio
    volumes:
      - $PWD/data:/tmp/data
    entrypoint: |
      /bin/sh -c "
        until $$(curl --output /dev/null --silent http://minio:9000); do
          echo 'Waiting for http://minio:9000'
          sleep 3
        done
        mc config host add manage-my-prison http://minio:9000 TEST_MINIO_ACCESS_KEY TEST_MINIO_SECRET_KEY
        mc rm -r --force manage-my-prison/test-bucket
        mc mb manage-my-prison/test-bucket
        mc mirror /tmp/data manage-my-prison/test-bucket/sandbox/
        exit 0
      "

  app:
    build: .
    networks:
      - hmpps
    container_name: app
    depends_on:
      - redis
      - hmpps-auth
      - minio
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - INGRESS_URL=http://localhost:3000
      - TOKEN_VERIFICATION_API_URL=http://hmpps-auth:8080/verification
      - SESSION_SECRET=app-insecure-default-session
      - API_CLIENT_ID=manage-my-prison-client
      - API_CLIENT_SECRET=clientsecret
      - AWS_DEFAULT_REGION=eu-west-2
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET_NAME=test-bucket
      - S3_ACCESS_KEY_ID=TEST_MINIO_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY=TEST_MINIO_SECRET_KEY

networks:
  hmpps:
