version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  minio:
    image: minio/minio
    command: server --console-address :9001 /data
    networks:
      - hmpps
    container_name: aws-s3-mock
    restart: always
    environment:
      - MINIO_ACCESS_KEY=TEST_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=TEST_MINIO_SECRET_KEY
    ports:
      - "9000:9000"
      - "9001:9001"

  createbuckets:
    image: minio/mc
    networks:
      - hmpps
    depends_on:
      - minio
    volumes:
      - $PWD/data:/tmp/data
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add manage-my-prison http://minio:9000 TEST_MINIO_ACCESS_KEY TEST_MINIO_SECRET_KEY;
      /usr/bin/mc rm -r --force manage-my-prison/test-bucket;
      /usr/bin/mc mb manage-my-prison/test-bucket;
      /usr/bin/mc mirror /tmp/data manage-my-prison/test-bucket/sandbox/;
      exit 0;
      "

  app:
    build: .
    networks:
      - hmpps
    depends_on: [redis]
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      # These will need to match new creds in the seed auth service auth
      - API_CLIENT_ID=client-id
      - API_CLIENT_SECRET=client-secret
      - SYSTEM_CLIENT_ID=system-client-id
      - SYSTEM_CLIENT_SECRET=system-client-secret

networks:
  hmpps:
