{{- if .Values.maintenanceMode -}}
{{/*
Replaces service created by generic-service subchart redirecting all traffic to default backend maintenance page
Notes:
- the generic-service chart's service cannot be modified in a way to point to a different set of pods/port combination
- turned on by setting `maintenanceMode` to true
- `generic-service.service.enabled` MUST be set to false because this service uses the same name and selector labels
*/}}
{{- if index .Values "generic-service" "service" "enabled" -}}
  {{ fail "`maintenanceMode` and `generic-service.service.enabled` cannot both be true!" }}
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: maintenance
      protocol: TCP
      name: http
  selector:
    {{- include "default-backend.selector-labels" . | nindent 4 }}
{{- end }}
