---
# used by templates to lookup the ECR secret and thence the ECR repo url
ecrSecretNamespace: manage-my-prison-dev
ecrSecretName: ecr-repo-manage-my-prison-dev

maintenanceMode: false  # when true, `generic-service.service.enabled` must be set to false

generic-service:
  nameOverride: manage-my-prison

  replicaCount: 4

  image:
    repository: quay.io/hmpps/manage-my-prison
    tag: app_version    # override at deployment time
    port: 3000

  service:
    enabled: true    # must be false if `maintenanceMode` is true

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: cert
    contextColour: green
    annotations:
      nginx.ingress.kubernetes.io/custom-http-errors: 403,418,503
      nginx.ingress.kubernetes.io/default-backend: default-backend
      nginx.ingress.kubernetes.io/server-snippet: |
        more_set_headers "Server: manage-my-prison";
        more_set_headers "Permissions-Policy: interest-cohort=()"
        more_set_headers "Referrer-Policy: same-origin";
        more_set_headers "Strict-Transport-Security: \"max-age=31536000; includeSubdomains\"";
        more_set_headers "X-Content-Type-Options: nosniff";
        more_set_headers "X-Frame-Options: sameorigin";
        more_set_headers "X-XSS-Protection: \"1; mode=block\"";

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  serviceAccountName: pod-internal

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  namespace_secrets:
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    manage-my-prison:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      SENTRY_DSN: "SENTRY_DSN"
    s3:
      S3_BUCKET_NAME: bucket_name
      S3_ACCESS_KEY_ID: access_key_id
      S3_SECRET_ACCESS_KEY: secret_access_key
      S3_BUCKET_ARN: bucket_arn

  allowlist:
    digital-studio: "217.33.148.210/32"
    102pf: "213.121.161.112/28"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    quantum1: "62.25.109.197/32"
    quantum2: "212.137.36.230/32"
    quantum3: "195.92.38.16/28"
    dxc_webproxy1: "195.92.38.20/32"
    dxc_webproxy2: "195.92.38.21/32"
    dxc_webproxy3: "195.92.38.22/32"
    dxc_webproxy4: "195.92.38.23/32"
    ark-nps-hmcts-ttp1: "195.59.75.0/24"
    ark-nps-hmcts-ttp2: "194.33.192.0/25"
    ark-nps-hmcts-ttp3: "194.33.193.0/25"
    ark-nps-hmcts-ttp4: "194.33.196.0/25"
    ark-nps-hmcts-ttp5: "194.33.197.0/25"
    digitalprisons1: "52.56.112.98/32"
    digitalprisons2: "52.56.118.154/32"
    moj-official-tgw-prod: "51.149.250.0/24"
    moj-official-tgw-preprod: "51.149.251.0/24"

generic-prometheus-alerts:
  targetApplication: manage-my-prison
  alertSeverity: manage-my-prison-dev
