---
generic-service:
  nameOverride: manage-my-prison

  replicaCount: 4

  image:
    repository: quay.io/hmpps/manage-my-prison
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: cert
    path: /
    annotations:
      external-dns.alpha.kubernetes.io/aws-weight: "100"
      nginx.ingress.kubernetes.io/server-snippet: |
        more_set_headers "Server: manage-my-prison";
        more_set_headers "Permissions-Policy: interest-cohort=()"
        more_set_headers "Referrer-Policy: same-origin";
        more_set_headers "Strict-Transport-Security: \"max-age=31536000; includeSubdomains\"";
        more_set_headers "X-Content-Type-Options: nosniff";
        more_set_headers "X-Frame-Options: sameorigin";
        more_set_headers "X-XSS-Protection: \"1; mode=block\"";

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  serviceAccountName: pod-internal

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  namespace_secrets:
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    manage-my-prison:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
    s3:
      S3_BUCKET_NAME: bucket_name
      S3_ACCESS_KEY_ID: access_key_id
      S3_SECRET_ACCESS_KEY: secret_access_key
      S3_BUCKET_ARN: bucket_arn

  allowlist:
    digital-studio: "217.33.148.210/32"
    102pf: "213.121.161.112/28"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    # cloudplatform-live1-1: "35.178.209.113/32"
    # cloudplatform-live1-2: "3.8.51.207/32"
    # cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: manage-my-prison
  alertSeverity: manage-my-prison-dev
